Fix buffer overrun in NT_GNU_PROPERTY_TYPE_0 parser
eliben/pyelftools pull request #538
Opened 2024-01-29 21:49 UTC by martijnthe

The `iter_notes` method has code to parse `NT_GNU_PROPERTY_TYPE_0` type notes. The contents of the note are interpreted as an array of `elffile.structs.Elf_Prop`s.

There was a bug where it would keep on parsing from the stream until the end of the *segment or section*. This is only correct if the note would be the last in the segment/section. In general, it should stop parsing until it reaches the end of the note's data buffer.

This PR fixes this bug.

Fixes: https://github.com/eliben/pyelftools/issues/534

2024-01-31 13:14 UTC, eliben commented
@sevaa

2024-01-31 14:52 UTC, sevaa commented
No objections. Compilers are a diverse bunch...

2024-02-01 01:02 UTC, eliben requested changes
Thanks for the fix and the thorough testing added. Just one small request

2024-02-01 01:02 UTC, eliben commented on elftools/elf/notes.py
> +            current_note_end = offset + note['n_descsz']
Can you add a small comment here explaining the semantics (the usage of `n_descsz`)? A link to some spec-like thing would be great too, if possible

2024-02-01 12:47 UTC, martijnthe commented
@eliben I've addressed your comment and resolved the conflicts with the other PR.

2024-02-01 13:10 UTC, eliben approved these changes

2024-02-01 13:10 UTC, merged