examples: Support DWARF5 filename decoding
eliben/pyelftools pull request #582
Opened 2024-12-01 02:27 UTC by cyyself

DWARF5 uses 0-indexed file_entry and directory_entry.  We should not skip index 0 when decoding the filename and the directory for DWARF5.

2024-12-02 14:13 UTC, sevaa commented
Makes sense.

2024-12-04 12:52 UTC, eliben requested changes
Thank you

Just a minor code style request

2024-12-04 12:52 UTC, eliben commented on examples/dwarf_lineprogram_filenames.py
> +    file_index -= 1 if lp_header.version < 5 else 0
Please rewrite this with simpler logic:

```
if ...version...:
  file_index -= 1
```

2024-12-04 12:52 UTC, eliben commented on examples/dwarf_lineprogram_filenames.py
> +    dir_index -= 1 if lp_header.version < 5 else 0
Same here

2024-12-04 18:11 UTC, cyyself commented
> Thank you
> 
> Just a minor code style request

Resolved now. Thanks!

2024-12-05 12:43 UTC, eliben approved these changes

2024-12-05 12:45 UTC, merged